[package]
name = "zakura-crosslink"
version = "0.1.0"
authors = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
description = "Zakura Trailing Finality Layer (Crosslink) lab prototype"

[dependencies]
zakura-chain = { path = "../zakura-chain", version = "6.0.0" }
zakura-state = { path = "../zakura-state" }

async-trait = "0.1"
blake3 = "1.8"
byteorder = { workspace = true }
ed25519-zebra = { workspace = true }
futures = { workspace = true }
hex = { workspace = true }
rand = { version = "0.8", default-features = false, features = ["std", "std_rng"] }
serde = { workspace = true, features = ["serde_derive"] }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["time", "rt-multi-thread", "macros", "sync"] }
tower = { workspace = true, features = ["util"] }
tracing = { workspace = true }
snow = { version = "0.10.0", default-features = false, features = ["use-curve25519", "use-chacha20poly1305", "use-blake2", "use-getrandom"] }

[dependencies.tenderlink]
version = "0.1.0"
git = "https://git.sr.ht/~azmr/stuff"
rev = "0e885095939781e2ce6320ab45097aeb85873449"
package = "tenderlink"

[dev-dependencies]
zakura-test = { path = "../zakura-test" }
